server:
  port: 8087

ribbon:
  ReadTimeout: 5000 #毫秒
  ConnectTimeout: 500 #毫秒

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false