server:
  port: 8088

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 500

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  routes:
    api-a:
      path: /api-consumer/**
      serviceId: consul-consumer
    api-b:
      path: /api-feign/**
      serviceId: consul-feign