server:
  port: 8084

spring:
  application:
    name: eureka-server2

eureka:
  instance:
    hostname: 127.0.0.1 #当hostname为ip地址时,prefer-ip-address = true的时候
    prefer-ip-address: true #prefer-ip-address = true 就可以将IP注册到Eureka Server上,而如果不配置就是机器的主机名
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
    register-with-eureka: true #注册中心高可用需要多个注册中心之间互相注册
    fetch-registry: true #fetch-registry打开才能从eureka拉取服务列表，ribbon才能做负载均衡